import { ArrowLeft, ArrowRight, Calendar, Trophy } from 'lucide-react';

interface Post { slug: string; title: string; date: string; description: string; content: string[] }
const posts: Post[] = [
  { slug: 'captain-picks-that-win-gameweeks', title: 'How to choose a captain that wins gameweeks', date: '12 February 2026', description: 'A practical framework for weighing form, fixtures and minutes before the deadline.', content: ['The captain decision is where a good FPL gameweek becomes a great one. Start with a player who is highly likely to play, then compare the quality of their fixture with recent attacking involvement.', 'Use the eye test as a final check, not the whole process. The best picks combine a strong role, a good matchup and a clear path to points.'] },
  { slug: 'inside-ai-fpl-predictions', title: 'What makes an AI FPL prediction useful?', date: '5 February 2026', description: 'Why confidence, context and clear reasoning matter more than a magic number.', content: ['Useful predictions explain the why. FPL AI weighs the information visible in your team screenshot and turns it into a focused recommendation you can act on.', 'No prediction is guaranteed. The goal is to make the decision clearer, compare your options and spot opportunities before your rivals do.'] },
  { slug: 'your-first-fpl-ai-analysis', title: 'Your first FPL AI analysis in three steps', date: '29 January 2026', description: 'Upload your team screenshot and get your captain, transfers and differentials in seconds.', content: ['Open your official FPL team page and take a clear screenshot showing your squad. Upload the JPG or PNG in the analyser, check the preview, then select Analyse My Team.', 'Free users get a sharp captain pick. Pro users unlock the complete breakdown, including transfers, predicted points, chip strategy and hidden gems.'] },
];

export default function Blog({ slug, onBack }: { slug?: string; onBack: () => void }) {
  const post = posts.find((item) => item.slug === slug);
  return <div className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-950/90"><div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between"><button onClick={onBack} className="flex items-center gap-2"><div className="w-9 h-9 rounded-xl bg-emerald-500 flex items-center justify-center"><Trophy className="w-5 h-5 text-slate-950" /></div><span className="font-bold">FPL <span className="text-emerald-400">AI</span></span></button><button onClick={onBack} className="text-slate-400 hover:text-white text-sm flex items-center gap-2"><ArrowLeft className="w-4 h-4" />Home</button></div></header><main className="max-w-5xl mx-auto px-4 py-14">{post ? <article className="max-w-3xl mx-auto"><p className="text-emerald-400 text-sm font-semibold mb-4">FPL AI JOURNAL</p><h1 className="text-4xl sm:text-5xl font-bold leading-tight">{post.title}</h1><p className="text-slate-500 text-sm mt-5 flex items-center gap-2"><Calendar className="w-4 h-4" />{post.date}</p><div className="mt-10 space-y-6 text-slate-300 leading-relaxed text-lg">{post.content.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></article> : <><div className="text-center mb-12"><p className="text-emerald-400 text-sm font-semibold uppercase tracking-[0.2em]">FPL AI Journal</p><h1 className="text-4xl sm:text-5xl font-bold mt-3">The edge, explained.</h1><p className="text-slate-400 mt-4">Practical FPL thinking for sharper decisions every gameweek.</p></div><div className="grid md:grid-cols-3 gap-5">{posts.map((item) => <article key={item.slug} className="bg-slate-900/70 border border-slate-800 rounded-2xl p-6 hover:border-emerald-500/40 transition-all"><p className="text-xs text-slate-500 flex items-center gap-2"><Calendar className="w-3.5 h-3.5" />{item.date}</p><h2 className="text-xl font-bold mt-4">{item.title}</h2><p className="text-slate-400 text-sm leading-relaxed mt-3">{item.description}</p><button onClick={() => window.history.pushState({}, '', `/blog/${item.slug}`)} className="text-emerald-400 text-sm font-semibold mt-6 flex items-center gap-2">Read article <ArrowRight className="w-4 h-4" /></button></article>)}</div></>}</main></div>;
}
